### PR TITLE
Compile all modules into dist

### PR DESCRIPTION
**Pull request by okcoker**
I'd like to try this out in a project that doesn't use react. This compiles the individual modules into the `dist` folder so they can be imported accordingly.

### CODE REVIEW

**Comment by alampros** [comment]
Have you tried building with this and using `yarn link` to test it out?

**Comment by okcoker** [comment]
@alampros yep I can import like so:

```js
import Confetti from 'react-confetti/dist/Confetti';
import { randomInt } from 'react-confetti/dist/utils';
```

**Comment by alampros** [comment]
Nice!

**Pull request merged**
