### PR TITLE
Confetti source shapes

### PR DESCRIPTION
**Pull request by cwstra**
Freshly rebuilt, still with the EmitterShape interface.

### CODE REVIEW

**Comment by cwstra** [comment]
Still relevant, waiting for review.

**Comment by cwstra** [comment]
Still relevant, waiting for review.

**Comment by cwstra** [comment]
Still relevant, waiting for review.

**Comment by alampros** [comment]
I'm not sure I'm understanding the use case for this. Can you explain why you would want this feature?

**Comment by alampros** [comment]
See #83 for history

**Comment by cwstra** [comment]
The motivating purpose was to be able to generate the confetti on an arbitrary line, in my case an angled party popper graphic. The other shapes were just me thinking of shapes that could have an IEmitterShape implementation.

**Comment by alampros** [comment]
I think this adds a lot of complexity for a feature not many people will use. I'm going to close it for now, but if anyone else pipes up we can definitely revisit it.

Thanks again for the contribution!

**Pull request closed without merging**
